name: CI

on:
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    - cron: '58 10 * * 6'

concurrency:
  group: $-$
  cancel-in-progress: true

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.93
    - uses: udoprog/trunk-action@v1
      with:
        args: build
    - run: cargo build --workspace --all-targets

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: udoprog/trunk-action@v1
      with:
        args: build
    - run: cargo test --workspace --all-targets
    - run: cargo test --workspace --doc

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: udoprog/trunk-action@v1
      with:
        args: build
    - run: cargo build --workspace --all-targets

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: udoprog/trunk-action@v1
      with:
        args: build
    - run: cargo clippy --workspace --all-targets -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --check --all
